### PR TITLE
Fix configure.ac, use dtv-scan-tables

### PR DESCRIPTION
**Pull request by jenslody**
Fixes used to build snapshot of gnome-dvb-daemon on Fedora.

### CODE REVIEW

**Comment by sebp** [comment]
Fixed in commits a52a4cb19a9575704d823af473a93012ef73f20f and dfe9eb38b856d11099c8519d81e5d7df8886040e

In the future, I'd appreciate if you could submit patches via https://bugzilla.gnome.org/page.cgi?id=browse.html&product=dvb-daemon

**Comment by jenslody** [comment]
Many thanks.
I will do so in the future.
Do you prefer pure patches or pull-requests ?

**Comment by sebp** [comment]
bugzilla.gnome.org has no built-in support for merge requests, therefore patches are preferred.

**Comment by gnomesysadmins** [comment]
Thank you for contributing to gnome-dvb-daemon!

gnome-dvb-daemon uses Bugzilla for code review.

If you have never contributed to GNOME before make sure you have read the
getting started documentation:
http://www.gnome.org/get-involved

Otherwise please visit
https://wiki.gnome.org/Newcomers/CodeContributionWorkflow
and follow the instructions there to upload your change to Bugzilla.

**Pull request closed without merging**
